(()=>{'use strict';
const API=window.POCHO_LAB_INTERNAL;if(!API)return;const M=window.Matter;const {Constraint,Composite}=M;
const {W,H,launchY,DT,LABEL,PHYS}=API.constants,$=s=>document.querySelector(s);
let world=null,stats=null,running=false,raf=0,last=0,acc=0,aiClock=0,logs=[],grab=null,grabbed=null,pointerHistory=[];
const cv=$('#observe-canvas'),ctx=cv?.getContext('2d');if(!cv||!ctx)return;
function setCanvas(){const dpr=Math.min(2,devicePixelRatio||1);cv.width=W*dpr;cv.height=H*dpr;cv.style.aspectRatio=`${W}/${H}`;ctx.setTransform(dpr,0,0,dpr,0,0)}setCanvas();addEventListener('resize',setCanvas);
const face=e=>e==='ごきげん'?'●‿●':e==='不機嫌'?'●︵●':'●―●',deco=d=>d==='リボン'?'🎀':d==='メガネ'?'👓':d==='王冠'?'👑':d==='芽'?'🌱':'';
function ensureSet(){if(world&&world.getCurrentShot()<+$('#observe-mode').value&&!world.getPreparedSet())world.prepareSet()}
function create(){stop();API.setSeed(+$('#seed').value||20260903);stats=API.emptyStats();stats.games=1;logs=[];world=API.createWorld(stats,+$('#observe-mode').value||30,$('#observe-ai').value,{onContact});ensureSet();updateObserverStats();draw()}
function start(){if(!world)create();running=true;last=performance.now();aiClock=0;$('#observe-start').textContent='一時停止';$('#observe-status').textContent='観察中';loop(last)}
function pause(){running=false;cancelAnimationFrame(raf);$('#observe-start').textContent='続行';$('#observe-status').textContent='一時停止中'}
function stop(){running=false;cancelAnimationFrame(raf);if(grab&&world)Composite.remove(world.getEngine().world,grab);grab=null;grabbed=null;world=null;stats=null;logs=[];if($('#observe-start'))$('#observe-start').textContent='開始 / リセット'}
function toggle(){running?pause():world?start():(create(),start())}
function loop(t){if(!running||!world)return;let delta=Math.min(50,t-last);last=t;acc+=delta;while(acc>=DT){world.step();acc-=DT;aiClock+=DT;maybeAI()}draw();updateObserverStats();raf=requestAnimationFrame(loop)}
function maybeAI(){if($('#observe-control').value!=='ai')return;const delay=+$('#observe-interval').value||900;if(aiClock<delay)return;aiClock=0;if(world.getCurrentShot()>=+$('#observe-mode').value)return;world.launchAuto();setTimeout(ensureSet,100)}
function point(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
function clamp(p,r=18){const top=H*.66;return{x:Math.max(r+4,Math.min(W-r-4,p.x)),y:Math.max(top+r+4,Math.min(H-r-8,p.y))}}
cv.addEventListener('pointerdown',e=>{if($('#observe-control').value!=='human'||!world)return;ensureSet();const set=world.getPreparedSet();if(!set)return;const p=point(e);let target=null,best=1e9;for(const b of set.bodies){const d=Math.hypot(p.x-b.position.x,p.y-b.position.y);if(d<=b.pocho.radius*1.55&&d<best){target=b;best=d}}if(!target)return;grabbed=target;const q=clamp(p,target.pocho.radius);pointerHistory=[{...q,t:performance.now()}];grab=Constraint.create({pointA:{x:q.x,y:q.y},bodyB:target,pointB:{x:0,y:0},length:0,stiffness:PHYS.DRAG_STIFFNESS||.22,damping:PHYS.DRAG_DAMPING||.10});Composite.add(world.getEngine().world,grab);cv.setPointerCapture?.(e.pointerId);$('#observe-status').textContent='3ぽちょを振り回して、離す！';e.preventDefault()});
cv.addEventListener('pointermove',e=>{if(!grab||!grabbed)return;const q=clamp(point(e),grabbed.pocho.radius);grab.pointA.x=q.x;grab.pointA.y=q.y;const n=performance.now();pointerHistory.push({...q,t:n});while(pointerHistory.length>10||(pointerHistory.length>2&&n-pointerHistory[0].t>180))pointerHistory.shift();e.preventDefault()});
function release(e){if(!grab||!world)return;Composite.remove(world.getEngine().world,grab);grab=null;let pv={x:0,y:0};if(pointerHistory.length>=2){const a=pointerHistory[0],z=pointerHistory.at(-1),dt=Math.max(16,z.t-a.t);pv={x:(z.x-a.x)/dt*16.67,y:(z.y-a.y)/dt*16.67};const m=Math.hypot(pv.x,pv.y);if(m>16.5){pv.x*=16.5/m;pv.y*=16.5/m}}world.releasePreparedSet(0,0,pv);grabbed=null;pointerHistory=[];setTimeout(ensureSet,500);updateObserverStats();draw();e?.preventDefault?.()}
cv.addEventListener('pointerup',release);cv.addEventListener('pointercancel',release);
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#fffaf5';ctx.fillRect(0,0,W,H);const zt=H*.66;ctx.fillStyle='rgba(247,243,236,.72)';ctx.fillRect(0,zt,W,H-zt);ctx.strokeStyle='rgba(120,105,95,.35)';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(0,zt);ctx.lineTo(W,zt);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(90,80,75,.55)';ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText('射出ゾーン',10,zt+18);ctx.strokeStyle='rgba(80,70,75,.18)';ctx.strokeRect(1,1,W-2,H-2);
 if(world){ctx.strokeStyle='rgba(110,92,100,.18)';ctx.lineWidth=5;ctx.lineCap='round';for(const b of world.getBonds()){ctx.beginPath();ctx.moveTo(b.bodyA.position.x,b.bodyA.position.y);ctx.lineTo(b.bodyB.position.x,b.bodyB.position.y);ctx.stroke()}const ps=world.getPreparedSet();if(ps){ctx.strokeStyle='rgba(110,92,100,.25)';for(const c of ps.links){ctx.beginPath();ctx.moveTo(c.bodyA.position.x,c.bodyA.position.y);ctx.lineTo(c.bodyB.position.x,c.bodyB.position.y);ctx.stroke()}}
 for(const b of world.getBodies()){const p=b.pocho;if(!p)continue;ctx.beginPath();ctx.fillStyle=p.hex||'#ddd';ctx.arc(b.position.x,b.position.y,p.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(80,65,70,.17)';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='rgba(60,50,55,.72)';ctx.font=`${Math.max(9,p.radius*.42)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(face(p.expression),b.position.x,b.position.y+1);const d=deco(p.decoration);if(d){ctx.font=`${Math.max(11,p.radius*.58)}px system-ui`;ctx.fillText(d,b.position.x,b.position.y-p.radius*.72)}}if(grab&&grabbed){ctx.strokeStyle='rgba(90,75,85,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(grab.pointA.x,grab.pointA.y);ctx.lineTo(grabbed.position.x,grabbed.position.y);ctx.stroke()}}}
function onContact(e){const actual=e.actualRule,row={...e.log,actualId:actual?.id||'',actual:actual?`${actual.id} ${actual.condition}`:'なし',shadow:e.shadow.map(x=>`${x.id}:${x.result}`).join(' / ')};logs.unshift(row);if(logs.length>200)logs.pop();renderLog();flash(e.log.outcome);renderObserverAnalytics()}
function flash(out){const el=$('#observe-last');el.textContent=out;el.className='observe-last '+out.toLowerCase();setTimeout(()=>{if(el.textContent===out)el.textContent=''},600)}
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderLog(){const box=$('#observe-log');box.innerHTML=logs.slice(0,60).map(x=>{const off=x.actualId&&API.isRuleDisabled(x.actualId);return `<div class="log-row ${x.outcome.toLowerCase()}"><div><b>${x.outcome}</b> <span>#${x.shot} / v=${x.relativeSpeed}</span></div><div>${x.layer==='none'?'判定なし':(LABEL[x.layer]||x.layer)+'：'+(x.rule||'')}</div><small>${esc(x.actual)}</small>${x.actualId?`<button class="mini observer-rule-toggle" data-rule-id="${x.actualId}">${off?'再有効化':'この条件を無効化'}</button>`:''}${x.roleCount?`<div class="role-log">役 ${x.roleCount}個 / 代表 #${x.roleRepresentative} ★${x.roleRarity} / +${Number(x.roleScore||0).toLocaleString()}<br><small>${esc(x.roles||'')}</small></div>`:''}<details><summary>裏成立 ${x.shadow?x.shadow.split(' / ').length:0}件</summary><code>${esc(x.shadow||'なし')}</code></details></div>`}).join('')||'<div class="empty-log">まだ接触ログはありません。</div>'}
const metric=(a,b)=>`<div class="metric"><small>${a}</small><b>${b}</b></div>`;
function renderObserverAnalytics(){if(!stats)return;const ab=stats.bodySamples?stats.bodySum/stats.bodySamples:0,ag=stats.groupSamples?stats.groupSum/stats.groupSamples:0,av=stats.popEvents?stats.popVictims/stats.popEvents:0;$('#observe-growth').innerHTML=metric('平均盤面個体',ab.toFixed(2))+metric('最大盤面個体',stats.maxBodies)+metric('平均グループ',ag.toFixed(2))+metric('最大グループ',stats.maxGroup)+metric('5体以上率',API.pct(stats.largeGroupSamples,stats.groupSamples))+metric('1POP平均消滅',av.toFixed(2));$('#observe-layer-table').innerHTML=API.layerTable(stats);$('#observe-speed-table').innerHTML=API.bucketTable(stats.speed);$('#observe-density-table').innerHTML=API.bucketTable(stats.density);$('#observe-phase-table').innerHTML=API.bucketTable(stats.phase);$('#observe-rule-table').innerHTML=API.ruleTable(stats);$('#observe-group-table').innerHTML=API.groupTable(stats);$('#observe-role-summary').innerHTML=API.roleSummary(stats);$('#observe-role-table').innerHTML=API.roleTable(stats)}
function updateObserverStats(){if(!world||!stats)return;const total=stats.contacts||0;$('#observe-shots').textContent=`${world.getCurrentShot()} / ${$('#observe-mode').value}`;$('#observe-bodies').textContent=world.getBodies().filter(b=>b.pocho?.launched).length;$('#observe-contacts').textContent=total;$('#observe-none').textContent=total?(stats.outcomes.NONE/total*100).toFixed(1)+'%':'—';$('#observe-stick').textContent=total?(stats.outcomes.STICK/total*100).toFixed(1)+'%':'—';$('#observe-pop').textContent=total?(stats.outcomes.POP/total*100).toFixed(1)+'%':'—';renderObserverAnalytics();if(world.getCurrentShot()>=+$('#observe-mode').value)$('#observe-status').textContent='射出上限到達（盤面観察は続行中）'}
$('#observe-start').onclick=toggle;$('#observe-reset').onclick=()=>{create();start()};$('#observe-control').onchange=()=>{$('#observe-human-help').hidden=$('#observe-control').value!=='human';aiClock=99999;ensureSet()};$('#observe-ai').onchange=()=>{create();start()};$('#observe-mode').onchange=()=>{create();start()};$('#observe-interval').oninput=()=>{$('#observe-interval-value').textContent=$('#observe-interval').value+'ms'};
$('#observe-export').onclick=()=>{if(!logs.length)return;const keys=['shot','outcome','layer','rule','relativeSpeed','density','groupA','groupB','groupAfter','popVictims','colorA','colorB','exprA','exprB','actual','shadow','roles','roleCount','roleRepresentative','roleRarity','roleScore'],text='\ufeff'+[keys.join(','),...logs.slice().reverse().map(x=>keys.map(k=>'"'+String(x[k]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='pocho_observer_log.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#observe-summary-export').onclick=()=>{if(!stats)return;const rows=[['metric','value'],['shots',stats.shots],['contacts',stats.contacts],['none_rate',API.pct(stats.outcomes.NONE,stats.contacts)],['stick_rate',API.pct(stats.outcomes.STICK,stats.contacts)],['pop_rate',API.pct(stats.outcomes.POP,stats.contacts)],['avg_bodies',stats.bodySamples?stats.bodySum/stats.bodySamples:0],['max_bodies',stats.maxBodies],['avg_group',stats.groupSamples?stats.groupSum/stats.groupSamples:0],['max_group',stats.maxGroup],['avg_pop_victims',stats.popEvents?stats.popVictims/stats.popEvents:0],['role_hits',stats.roleHits],['score_events',stats.scoreEvents],['avg_roles_per_score_event',stats.scoreEvents?stats.roleHits/stats.scoreEvents:0],['max_roles_one_event',stats.maxRolesOneEvent],['total_role_score',stats.totalRoleScore],['max_score_event',stats.maxScoreEvent]],text='\ufeff'+rows.map(r=>r.join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='pocho_observer_summary.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#observe-log').addEventListener('click',e=>{const b=e.target.closest?.('.observer-rule-toggle');if(!b)return;API.toggleRuleDisabled(b.dataset.ruleId);API.updateConfigUi?.();renderLog();renderObserverAnalytics();$('#observe-status').textContent=`${b.dataset.ruleId} を${API.isRuleDisabled(b.dataset.ruleId)?'個別OFF':'再有効化'}（次の接触から反映）`});$('#observe-rule-table').addEventListener('click',e=>{if(e.target.closest?.('.rule-toggle'))setTimeout(()=>{renderObserverAnalytics();renderLog()},0)});
$('#observe-human-help').textContent='射出ゾーン内の3ぽちょの好きな1体を掴み、振り回して離してください。3体で1カウントです。';$('#observe-human-help').hidden=false;$('#observe-interval-value').textContent=$('#observe-interval').value+'ms';create();draw();
})();
