(()=>{'use strict';
const API=window.POCHO_LAB_INTERNAL;if(!API)return;
const {W,H,launchY,DT,LABEL}=API.constants;
const $=s=>document.querySelector(s);
let world=null,stats=null,running=false,raf=0,last=0,acc=0,aiClock=0,currentDesc=null,drag=null,logs=[];
const cv=$('#observe-canvas'),ctx=cv?.getContext('2d');if(!cv||!ctx)return;
function setCanvas(){const dpr=Math.min(2,window.devicePixelRatio||1);cv.width=W*dpr;cv.height=H*dpr;cv.style.aspectRatio=`${W}/${H}`;ctx.setTransform(dpr,0,0,dpr,0,0)}setCanvas();window.addEventListener('resize',setCanvas);
function face(e){return e==='ごきげん'?'●‿●':e==='不機嫌'?'●︵●':'●―●'}
function deco(d){return d==='リボン'?'🎀':d==='メガネ'?'👓':d==='王冠'?'👑':d==='芽'?'🌱':''}
function prepare(){if(!currentDesc&&world)currentDesc=world.makeDescriptor()}
function create(){stop();API.setSeed(+$('#seed').value||20260903);stats=API.emptyStats();stats.games=1;logs=[];currentDesc=null;const shots=+$('#observe-mode').value||30,ai=$('#observe-ai').value;world=API.createWorld(stats,shots,ai,{onContact:e=>onContact(e)});prepare();updateObserverStats();draw()}
function start(){if(!world)create();running=true;last=performance.now();aiClock=0;$('#observe-start').textContent='一時停止';$('#observe-status').textContent='観察中';loop(last)}
function pause(){running=false;cancelAnimationFrame(raf);$('#observe-start').textContent='続行';$('#observe-status').textContent='一時停止中'}
function stop(){running=false;cancelAnimationFrame(raf);world=null;stats=null;logs=[];drag=null;currentDesc=null;if($('#observe-start'))$('#observe-start').textContent='開始 / リセット'}
function toggle(){if(running)pause();else if(world)start();else{create();start()}}
function loop(t){if(!running||!world)return;let delta=Math.min(50,t-last);last=t;acc+=delta;while(acc>=DT){world.step();acc-=DT;aiClock+=DT;maybeAI()}draw();updateObserverStats();raf=requestAnimationFrame(loop)}
function maybeAI(){const mode=$('#observe-control').value;if(mode!=='ai')return;const delay=+$(`#observe-interval`).value||900;if(aiClock<delay)return;aiClock=0;if(world.getCurrentShot()>=+$('#observe-mode').value)return;world.launchAuto();prepare()}
function launchHuman(dx,dy){if(!world||world.getCurrentShot()>=+$('#observe-mode').value)return;const d=Math.min(120,Math.hypot(dx,dy));if(d<8)return;const scale=d/120*16.5,mag=Math.max(1,Math.hypot(dx,dy));const vx=-dx/mag*scale,vy=-dy/mag*scale;world.launchVector(vx,vy,currentDesc||world.makeDescriptor());currentDesc=world.makeDescriptor();updateObserverStats()}
function point(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
cv.addEventListener('pointerdown',e=>{if($('#observe-control').value!=='human'||!world)return;const p=point(e);if(Math.hypot(p.x-W/2,p.y-launchY)>75)return;drag=p;cv.setPointerCapture?.(e.pointerId);draw()});
cv.addEventListener('pointermove',e=>{if(!drag)return;drag=point(e);draw()});
cv.addEventListener('pointerup',e=>{if(!drag)return;const p=point(e),dx=p.x-W/2,dy=p.y-launchY;drag=null;launchHuman(dx,dy);draw()});
cv.addEventListener('pointercancel',()=>{drag=null;draw()});
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#fffaf5';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(80,70,75,.18)';ctx.lineWidth=2;ctx.strokeRect(1,1,W-2,H-2);
 if(world){ctx.strokeStyle='rgba(110,92,100,.18)';ctx.lineWidth=2;for(const b of world.getBonds()){ctx.beginPath();ctx.moveTo(b.bodyA.position.x,b.bodyA.position.y);ctx.lineTo(b.bodyB.position.x,b.bodyB.position.y);ctx.stroke()}
 for(const b of world.getBodies()){const p=b.pocho;if(!p)continue;ctx.beginPath();ctx.fillStyle=p.hex||'#ddd';ctx.arc(b.position.x,b.position.y,p.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(80,65,70,.17)';ctx.stroke();ctx.fillStyle='rgba(60,50,55,.72)';ctx.font=`${Math.max(9,p.radius*.42)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(face(p.expression),b.position.x,b.position.y+1);const d=deco(p.decoration);if(d){ctx.font=`${Math.max(11,p.radius*.58)}px system-ui`;ctx.fillText(d,b.position.x,b.position.y-p.radius*.72)}}}
 if(currentDesc&&world&&world.getCurrentShot()<+$('#observe-mode').value){const r=currentDesc.radius;ctx.beginPath();ctx.fillStyle=currentDesc.hex;ctx.arc(W/2,launchY,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(60,50,55,.72)';ctx.font=`${Math.max(9,r*.42)}px system-ui`;ctx.fillText(face(currentDesc.expression),W/2,launchY+1);const d=deco(currentDesc.decoration);if(d){ctx.font=`${Math.max(11,r*.58)}px system-ui`;ctx.fillText(d,W/2,launchY-r*.72)}}
 if(drag){ctx.strokeStyle='rgba(90,75,85,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W/2,launchY);ctx.lineTo(drag.x,drag.y);ctx.stroke();ctx.fillStyle='rgba(90,75,85,.45)';ctx.beginPath();ctx.arc(drag.x,drag.y,7,0,Math.PI*2);ctx.fill()}}
function onContact(e){const actual=e.actualRule;const row={...e.log,actualId:actual?.id||'',actual:actual?`${actual.id} ${actual.condition}`:'なし',shadow:e.shadow.map(x=>`${x.id}:${x.result}`).join(' / ')};logs.unshift(row);if(logs.length>200)logs.pop();renderLog();flash(e.log.outcome);renderObserverAnalytics()}
function flash(out){const el=$('#observe-last');el.textContent=out;el.className='observe-last '+out.toLowerCase();setTimeout(()=>{if(el.textContent===out)el.textContent=''},600)}
function renderLog(){const box=$('#observe-log');box.innerHTML=logs.slice(0,60).map((x,i)=>{const off=x.actualId&&API.isRuleDisabled(x.actualId);return `<div class="log-row ${x.outcome.toLowerCase()}"><div><b>${x.outcome}</b> <span>#${x.shot} / v=${x.relativeSpeed}</span></div><div>${x.layer==='none'?'判定なし':(LABEL[x.layer]||x.layer)+'：'+(x.rule||'')}</div><small>${escapeHtml(x.actual)}</small>${x.actualId?`<button class="mini observer-rule-toggle" data-rule-id="${x.actualId}">${off?'再有効化':'この条件を無効化'}</button>`:''}<details><summary>裏成立 ${x.shadow?x.shadow.split(' / ').length:0}件</summary><code>${escapeHtml(x.shadow||'なし')}</code></details></div>`}).join('')||'<div class="empty-log">まだ接触ログはありません。</div>'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function metric(a,b){return `<div class="metric"><small>${a}</small><b>${b}</b></div>`}
function renderObserverAnalytics(){if(!stats)return;const avgBodies=stats.bodySamples?stats.bodySum/stats.bodySamples:0,avgGroup=stats.groupSamples?stats.groupSum/stats.groupSamples:0,avgVictims=stats.popEvents?stats.popVictims/stats.popEvents:0;$('#observe-growth').innerHTML=metric('平均盤面個体',avgBodies.toFixed(2))+metric('最大盤面個体',stats.maxBodies)+metric('平均グループ',avgGroup.toFixed(2))+metric('最大グループ',stats.maxGroup)+metric('5体以上率',API.pct(stats.largeGroupSamples,stats.groupSamples))+metric('1POP平均消滅',avgVictims.toFixed(2));$('#observe-layer-table').innerHTML=API.layerTable(stats);$('#observe-speed-table').innerHTML=API.bucketTable(stats.speed);$('#observe-density-table').innerHTML=API.bucketTable(stats.density);$('#observe-phase-table').innerHTML=API.bucketTable(stats.phase);$('#observe-rule-table').innerHTML=API.ruleTable(stats);$('#observe-group-table').innerHTML=API.groupTable(stats)}
function updateObserverStats(){if(!world||!stats)return;const total=stats.contacts||0;$('#observe-shots').textContent=`${world.getCurrentShot()} / ${$('#observe-mode').value}`;$('#observe-bodies').textContent=world.getBodies().length;$('#observe-contacts').textContent=total;$('#observe-none').textContent=total?`${(stats.outcomes.NONE/total*100).toFixed(1)}%`:'—';$('#observe-stick').textContent=total?`${(stats.outcomes.STICK/total*100).toFixed(1)}%`:'—';$('#observe-pop').textContent=total?`${(stats.outcomes.POP/total*100).toFixed(1)}%`:'—';renderObserverAnalytics();if(world.getCurrentShot()>=+$('#observe-mode').value)$('#observe-status').textContent='射出上限到達（盤面観察は続行中）'}
$('#observe-start').onclick=toggle;$('#observe-reset').onclick=()=>{create();start()};$('#observe-control').onchange=()=>{$('#observe-human-help').hidden=$('#observe-control').value!=='human';aiClock=99999};$('#observe-ai').onchange=()=>{create();start()};$('#observe-mode').onchange=()=>{create();start()};$('#observe-interval').oninput=()=>{$('#observe-interval-value').textContent=$('#observe-interval').value+'ms'};
$('#observe-export').onclick=()=>{if(!logs.length)return;const keys=['shot','outcome','layer','rule','relativeSpeed','density','groupA','groupB','groupAfter','popVictims','colorA','colorB','exprA','exprB','actual','shadow'];const text='\ufeff'+[keys.join(','),...logs.slice().reverse().map(x=>keys.map(k=>'"'+String(x[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='pocho_observer_log.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#observe-summary-export').onclick=()=>{if(!stats)return;const rows=[['metric','value'],['shots',stats.shots],['contacts',stats.contacts],['none_rate',API.pct(stats.outcomes.NONE,stats.contacts)],['stick_rate',API.pct(stats.outcomes.STICK,stats.contacts)],['pop_rate',API.pct(stats.outcomes.POP,stats.contacts)],['avg_bodies',stats.bodySamples?stats.bodySum/stats.bodySamples:0],['max_bodies',stats.maxBodies],['avg_group',stats.groupSamples?stats.groupSum/stats.groupSamples:0],['max_group',stats.maxGroup],['avg_pop_victims',stats.popEvents?stats.popVictims/stats.popEvents:0]];const text='\ufeff'+rows.map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='pocho_observer_summary.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#observe-log').addEventListener('click',e=>{const b=e.target.closest?.('.observer-rule-toggle');if(!b)return;API.toggleRuleDisabled(b.dataset.ruleId);renderLog();renderObserverAnalytics();$('#observe-status').textContent=`${b.dataset.ruleId} を${API.isRuleDisabled(b.dataset.ruleId)?'個別OFF':'再有効化'}（次の接触から反映）`});
$('#observe-rule-table').addEventListener('click',e=>{if(e.target.closest?.('.rule-toggle'))setTimeout(()=>{renderObserverAnalytics();renderLog()},0)});
$('#observe-human-help').hidden=false;$('#observe-interval-value').textContent=$('#observe-interval').value+'ms';create();draw();
})();
